/* eslint-disable @next/next/no-img-element */
import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage,
} from 'next'
import Head from 'next/head'
import { signOut, useSession } from 'next-auth/react'

import { getTweetLightSession } from '@/utils/getTweetLightSession'
import { NewTweet } from '@/components/NewTweet'
import ListOfTweets from '@/components/ListOfTweets'

const Home: NextPage = () => {
  const { data: session } = useSession()

  if (!session || !session.user) {
    return null
  }

  return (
    <>
      <Head>
        <title>TweetLight</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="flex justify-center bg-slate-600">
          <div className="flex justify-between items-center w-full md:w-3/5 py-5">
            <div>TweetLight</div>
            <div>User</div>
          </div>
        </nav>
        <section className="flex justify-center py-10">
          <div className="w-full md:w-3/5">
            <NewTweet />
            <ListOfTweets />
          </div>
        </section>
        Signed in as {session?.user?.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (
  ctx: GetServerSidePropsContext
) => {
  const session = await getTweetLightSession(ctx)

  if (!session) {
    return {
      redirect: { destination: '/login', permanent: false },
    }
  }

  return {
    props: {
      session,
    },
  }
}

export default Home
