/* eslint-disable @next/next/no-img-element */
import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage,
} from 'next'
import Head from 'next/head'
import { useSession } from 'next-auth/react'

import { getTweetLightSession } from '@/utils/getTweetLightSession'
import { NewTweet } from '@/components/NewTweet'
import ListOfTweets from '@/components/ListOfTweets'
import { NavBar } from '@/components/NavBar'

const Home: NextPage = () => {
  const { data: session } = useSession()

  if (!session || !session.user) {
    return null
  }

  return (
    <>
      <Head>
        <title>TweetLight</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <section className="flex justify-center py-10">
          <div className="w-full md:w-3/5">
            <NewTweet />
            <ListOfTweets />
          </div>
        </section>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (
  ctx: GetServerSidePropsContext
) => {
  const session = await getTweetLightSession(ctx)

  if (!session) {
    return {
      redirect: { destination: '/login', permanent: false },
    }
  }

  return {
    props: {
      session,
    },
  }
}

export default Home
