import Head from 'next/head'
import { PropsWithChildren, FC } from 'react'
import { NavBar } from './NavBar'

export const Page: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>TweetLight</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <div className="flex justify-center py-10">
          <div className="w-full md:w-3/5 flex flex-col items-center">
            {children}
          </div>
        </div>
      </main>
    </>
  )
}
